---
# SPDX-License-Identifier: MIT OR LGPL-2.0-or-later
# SPDX-FileCopyrightText: 2018 Philip Chimento <philip.chimento@gmail.com>
rules:
  require-jsdoc: "off"
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2022