---
# SPDX-License-Identifier: MIT OR LGPL-2.0-or-later
# SPDX-FileCopyrightText: 2020 Evan Welsh <contact@evanwelsh.com>
rules:
  jsdoc/require-param: 'off'
  jsdoc/require-param-type: 'off'
  jsdoc/require-returns: 'off'
  jsdoc/require-jsdoc: 'off'
  jsdoc/check-tag-names: 'off'
  jsdoc/check-param-names: 'off'
