---
env:
  es6: true
extends: 'eslint:recommended'
rules:
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  block-scoped-var: error
  brace-style: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  indent:
    - error
    - 4
    - ignoredNodes:
      # Allow not indenting the body of GObject.registerClass, since in the
      # future it's intended to be a decorator
      - 'CallExpression[callee.object.name=GObject][callee.property.name=registerClass] > ClassExpression:first-child'
      # Allow dedenting chained member expressions
      MemberExpression: 'off'
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  keyword-spacing:
    - error
    - before: true
      after: true
  linebreak-style:
    - error
    - unix
  no-constant-condition:
    - error
    - checkLoops: false
  no-empty:
    - error
    - allowEmptyCatch: true
  no-implicit-coercion:
    - error
    - allow:
      - '!!'
  no-prototype-builtins: 'off'
  no-restricted-properties:
    - error
    - object: Lang
      property: bind
      message: Use arrow notation or Function.prototype.bind()
    - object: Lang
      property: Class
      message: Use ES6 classes
  no-tabs: error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^unused
  nonblock-statement-body-position:
    - error
    - below
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing: error
  prefer-template: error
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks: error
  space-infix-ops:
    - error
    - int32Hint: false
globals:
  ARGV: false
  Debugger: false
  GIRepositoryGType: false
  imports: false
  Intl: false
  log: false
  logError: false
  print: false
  printerr: false
  window: false
parserOptions:
  ecmaVersion: 2017
