# SPDX-FileCopyrightText: 2018 Claudio André

FROM alpine:latest
MAINTAINER Claudio André (c) 2018 V1.0

LABEL architecture="x86_64"
LABEL version="1.0"
LABEL description="Docker image to run CI for GNOME GJS (JavaScript bindings for GNOME)."

RUN apk add --no-cache python3 git
RUN python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel
RUN pip3 install --no-cache --upgrade cpplint
RUN mkdir -p /cwd

CMD ["/bin/bash"]
