# === Build stage ===

FROM fedora:32 AS build
ARG MOZJS_BRANCH=mozjs68
ARG BUILD_OPTS=

ENV SHELL=/bin/bash

RUN dnf -y install 'dnf-command(builddep)' clang-devel cmake git llvm-devel \
    make ninja-build which
RUN dnf -y builddep mozjs68 sysprof

WORKDIR /root

ADD https://include-what-you-use.org/downloads/include-what-you-use-0.14.src.tar.gz /root/
RUN tar xzf include-what-you-use-0.14.src.tar.gz
RUN mkdir -p include-what-you-use/_build

WORKDIR /root/include-what-you-use/_build

RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr ..
RUN ninja
RUN DESTDIR=/root/iwyu-install ninja install

WORKDIR /root

RUN git clone --depth 1 https://gitlab.gnome.org/GNOME/sysprof.git

WORKDIR /root/sysprof

RUN meson _build -Dprefix=/usr -Dlibdir=lib64 -Denable_examples=false \
    -Denable_gtk=false -Denable_tests=false -Denable_tools=false -Dhelp=false \
    -Dlibsysprof=false -Dwith_sysprofd=none
RUN ninja -C _build
RUN DESTDIR=/root/sysprof-install ninja -C _build install

WORKDIR /root

RUN git clone --depth 1 https://github.com/ptomato/mozjs.git -b ${MOZJS_BRANCH}
RUN mkdir -p mozjs/_build

WORKDIR /root/mozjs/_build

RUN ../js/src/configure --prefix=/usr --libdir=/usr/lib64 --disable-jemalloc \
    --enable-posix-nspr-emulation --enable-unaligned-private-values \
    --with-system-zlib --with-intl-api --enable-debug AUTOCONF=autoconf \
    ${BUILD_OPTS}
RUN make -j$(nproc)
RUN DESTDIR=/root/mozjs-install make install
RUN rm -f /root/mozjs-install/usr/lib64/libjs_static.ajs

# === Actual Docker image ===

FROM fedora:32

ENV SHELL=/bin/bash

# List is comprised of base dependencies for CI scripts, gjs, and debug packages
# needed for informative stack traces, e.g. in Valgrind.
#
# Do everything in one RUN command so that the dnf cache is not cached in the
# final Docker image.
RUN dnf -y install --enablerepo=fedora-debuginfo,updates-debuginfo \
    binutils cairo-debuginfo cairo-debugsource cairo-gobject-devel clang \
    compiler-rt dbus-daemon diffutils fontconfig-debuginfo \
    fontconfig-debugsource gcc-c++ git glib2-debuginfo glib2-debugsource \
    glib2-devel glibc-debuginfo glibc-debuginfo-common gnome-desktop-testing \
    gobject-introspection-debuginfo gobject-introspection-debugsource \
    gobject-introspection-devel gtk3-debuginfo gtk3-debugsource gtk3-devel \
    gtk4-debuginfo gtk4-debugsource gtk4-devel lcov libasan libubsan libtsan \
    meson-0.54.0-1.fc32 ninja-build pkgconf readline-devel systemtap-sdt-devel \
    valgrind which Xvfb xz && \
    dnf clean all && rm -rf /var/cache/dnf

COPY --from=build /root/mozjs-install/usr /usr
COPY --from=build /root/sysprof-install/usr /usr
COPY --from=build /root/iwyu-install/usr /usr
RUN ln -s /usr/bin/iwyu_tool.py /usr/bin/iwyu_tool

# Enable sudo for wheel users
RUN sed -i -e 's/# %wheel/%wheel/' -e '0,/%wheel/{s/%wheel/# %wheel/}' \
    /etc/sudoers

ENV HOST_USER_ID 5555
RUN useradd -u $HOST_USER_ID -G wheel -ms /bin/bash user

USER user
WORKDIR /home/user

ENV LANG C.UTF-8
