---
# SPDX-License-Identifier: MIT OR LGPL-2.0-or-later
# SPDX-FileCopyrightText: 2018 Philip Chimento <philip.chimento@gmail.com>
env:
  jasmine: true
rules:
  no-restricted-globals:
    - error
    - name: fdescribe
      message: Do not commit fdescribe(). Use describe() instead.
    - name: fit
      message: Do not commit fit(). Use it() instead.
  no-restricted-syntax:
    - error
    - selector: CallExpression[callee.name="it"] > ArrowFunctionExpression
      message: Arrow functions can mess up some Jasmine APIs. Use function () instead
    - selector: CallExpression[callee.name="beforeEach"] > ArrowFunctionExpression
      message: Arrow functions can mess up some Jasmine APIs. Use function () instead
    - selector: CallExpression[callee.name="afterEach"] > ArrowFunctionExpression
      message: Arrow functions can mess up some Jasmine APIs. Use function () instead
    - selector: CallExpression[callee.name="beforeAll"] > ArrowFunctionExpression
      message: Arrow functions can mess up some Jasmine APIs. Use function () instead
    - selector: CallExpression[callee.name="afterAll"] > ArrowFunctionExpression
      message: Arrow functions can mess up some Jasmine APIs. Use function () instead
overrides:
  - files:
      - matchers.js
      - minijasmine.js
      - minijasmine-executor.js
      - testAsync.js
      - testAsyncMainloop.js
      - testCairoModule.js
      - testConsole.js
      - testESModules.js
      - testEncoding.js
      - testGLibLogWriter.js
      - testTimers.js
      - testUtility.js
      - testWeakRef.js
      - modules/importmeta.js
      - modules/exports.js
      - modules/greet.js
      - modules/networkURI.js
      - modules/say.js
      - modules/scaryURI.js
      - modules/sideEffect4.js
    parserOptions:
      sourceType: module
