---
# SPDX-License-Identifier: MIT OR LGPL-2.0-or-later
# SPDX-FileCopyrightText: 2020 Evan Welsh <contact@evanwelsh.com>
extends: ../../.eslintrc.yml
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2022
globals:
  ARGV: off
  Debugger: readonly
  GIRepositoryGType: off
  imports: off
  Intl: readonly
  log: off
  logError: off
  print: off
  printerr: off

  atob: readonly
  compileInternalModule: readonly
  compileModule: readonly
  getRegistry: readonly
  getSourceMapRegistry: readonly
  loadResourceOrFile: readonly
  loadResourceOrFileAsync: readonly
  moduleGlobalThis: readonly
  parseURI: readonly
  resolveRelativeResourceOrFile: readonly
  setGlobalModuleLoader: readonly
  setModulePrivate: readonly
  uriExists: readonly
